raw_tiff_path = fullfile('path_to_data/');
extract_path = fullfile('path_to_save/');

convertScanImageTiffToVolume( ...
    raw_tiff_path, ...
    extract_path, ...
    'trim_pixels', [6 6 17 0] ...
);
